module:
  block: 0
  block_content: 0
  breakpoint: 0
  captcha: 0
  ckeditor: 0
  config: 0
  contact: 0
  ctools: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  field: 0
  field_layout: 0
  field_ui: 0
  file: 0
  filter: 0
  gendered_text_api: 0
  gendered_text_customizations: 0
  google_analytics: 0
  honeypot: 0
  image: 0
  layout_discovery: 0
  link: 0
  mailgun: 0
  mailsystem: 0
  menu_ui: 0
  nocurrent_pass: 0
  node: 0
  notification: 0
  options: 0
  page_cache: 0
  path: 0
  redirect: 0
  registration_role: 0
  system: 0
  taxonomy: 0
  taxonomy_access_fix: 0
  text: 0
  token: 0
  toolbar: 0
  user: 0
  views_ui: 0
  workbench: 0
  workbench_moderation: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  minimal: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  adminimal_theme: 0
  bootstrap: 0
  gendered_theme: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
