schemas:
  bootstrap: 8000
  gendered_theme: 8000
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://gendered_drupal.test/themes/bootstrap/favicon.ico'
  use_default: 0
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: 0
  node_user_picture: false
logo:
  path: ''
  url: ''
  use_default: 0
fluid_container: 1
table: ''
