smtp_on: true
smtp_host: smtp.mailgun.org
smtp_hostbackup: ''
smtp_port: '25'
smtp_protocol: tls
smtp_username: postmaster@sandboxb492616ce7d1495ab4a2631fb0c70ac7.mailgun.org
smtp_password: 59fc1d6c5b560c4bfd27210aba6eacd3-833f99c3-84aa919f
smtp_from: ''
smtp_fromname: ''
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '0'
smtp_test_address: ''
smtp_debugging: true
prev_mail_system: php_mail
_core:
  default_config_hash: WEa5Ex_IeAcm6Bm0hmQ4vU_nDwJDB8hW-vxT1qpGIbM
